services:
  auth-service:
    build: 
      context: ../authService
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - SPRING_DATA_MONGODB_URI=${DB_CONNECTION_URL}
      - SERVER_PORT=${AUTH_PORT}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_LOG_PATH=/var/log/authentication-service
    volumes:
      - ${LOG_PATH}:/var/log/authentication-service
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${LOG_PATH}:/var/log/logstash
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
