services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    ports:
      - ${ES_PORT}:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data: