spring:
  application:
    name: AuthenticationService
  data:
      mongodb:
        uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongouser:password123@ec2-65-2-37-196.ap-south-1.compute.amazonaws.com:27018/authentication_db?authSource=admin}
      redis:
        host: ${SPRING_DATA_REDIS_HOST:ec2-65-2-37-196.ap-south-1.compute.amazonaws.com}
        port: ${SPRING_DATA_REDIS_PORT:6379}
        password: ${SPRING_DATA_REDIS_PASSWORD:password123}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true
redis:
  cache:
    ttl-hours: 1
server:
  port: ${SERVER_PORT:8081}
jwt:
  secret: SDDsds1sd231asd1d1gds12312asdasd873sjdasd1d12312df3123gfgdfgfg3123asdasd1ddsg3t6
  expiration: 3600000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-}] - %msg%n"
  file:
    name: ${SPRING_LOG_PATH}/logs/authentication-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 5
      total-size-cap: 25MB
      clean-history-on-start: true
      file-name-pattern: ${SPRING_LOG_PATH}/logs/archived/authentication-service.%d{yyyy-MM-dd}.%i.log