services:
  gateway-service:
    build: 
      context: ../APIGateway
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - SERVER_PORT=${GATEWAY_PORT}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_LOG_PATH=/var/log/gateway-service
      - SPRING_AUTH_SERVICE=${AUTH_SERVICE}
    volumes:
      - ${LOG_PATH}:/var/log/gateway-service
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${LOG_PATH}:/var/log/logstash
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
